/* 🤖 this file was generated by svg-to-ts*/

import { SvgIcon } from './svg/svg-icon.model';

export type IconNameSubset<T extends Readonly<SvgIcon[]>> = T[number]['name'];

export * from './svg/svg-close.icon';
export * from './svg/svg-logo.icon';
export * from './svg/svg-notification.icon';
export * from './svg/svg-plus.icon';
export * from './svg/svg-settings.icon';
export * from './svg/svg-icon.model';
