/* 🤖 this file was generated by svg-to-ts*/

import { SvgIcon } from './svg/svg-icon.model';

export type IconNameSubset<T extends Readonly<SvgIcon[]>> = T[number]['name'];

export * from './svg/svg-notification.icon';
export * from './svg/svg-plus-bold.icon';
export * from './svg/svg-settings.icon';
export * from './svg/svg-user-avatar-1.icon';
export * from './svg/svg-user-avatar-2.icon';
export * from './svg/svg-user-avatar-3.icon';
export * from './svg/svg-user-avatar-4.icon';
export * from './svg/svg-user-avatar-5.icon';
export * from './svg/svg-icon.model';
