/* 🤖 this file was generated by svg-to-ts*/

import { SvgIcon } from './svg/svg-icon.model';

export type IconNameSubset<T extends Readonly<SvgIcon[]>> = T[number]['name'];

export * from './svg/svg-add-image.icon';
export * from './svg/svg-arrow-left.icon';
export * from './svg/svg-chart-arrow-down.icon';
export * from './svg/svg-chart-arrow-flat.icon';
export * from './svg/svg-chart-arrow-up.icon';
export * from './svg/svg-check.icon';
export * from './svg/svg-close.icon';
export * from './svg/svg-decentr-hub.icon';
export * from './svg/svg-delete.icon';
export * from './svg/svg-dropdown-expand.icon';
export * from './svg/svg-dynamics-negative.icon';
export * from './svg/svg-dynamics-positive.icon';
export * from './svg/svg-edit.icon';
export * from './svg/svg-expand-more.icon';
export * from './svg/svg-follow.icon';
export * from './svg/svg-import-account.icon';
export * from './svg/svg-import.icon';
export * from './svg/svg-information.icon';
export * from './svg/svg-like.icon';
export * from './svg/svg-lock-account.icon';
export * from './svg/svg-lock.icon';
export * from './svg/svg-logo-icon-orange.icon';
export * from './svg/svg-logo-icon-pink.icon';
export * from './svg/svg-logo-icon.icon';
export * from './svg/svg-logo.icon';
export * from './svg/svg-pdv-rate-icon.icon';
export * from './svg/svg-plus.icon';
export * from './svg/svg-publish.icon';
export * from './svg/svg-receive-coin.icon';
export * from './svg/svg-reload.icon';
export * from './svg/svg-send-coin.icon';
export * from './svg/svg-settings.icon';
export * from './svg/svg-signal.icon';
export * from './svg/svg-trash.icon';
export * from './svg/svg-icon.model';
