/* 🤖 this file was generated by svg-to-ts*/
export const svgDynamicsPositive: {
  name: 'dynamics-positive';
  data: string;
} = {
  name: 'dynamics-positive',
  data: `<svg viewBox="0 0 139 30" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1 27l18.028-14.722L31.426 23l10.499-8.165L67.887.917l29.081 13.918L111.98 7.83 137 15" stroke="#8FD2C8"/><path opacity=".1" fill-rule="evenodd" clip-rule="evenodd" d="M1 27.288l18.028-14.784L31.426 23l10.499-8.036L67.887 1.126l29.081 13.838 15.012-6.966L137 15v13.953H1v-1.665z" fill="url(#paint1_linear)"/><rect x="134" y="12" width="6" height="6" rx="3" fill="#65B0A2" stroke="#fff" stroke-width="2"/><defs><linearGradient id="paint0_linear" x1="137" y1=".917" x2="1" y2=".917" gradientUnits="userSpaceOnUse"><stop stop-color="#8FD2C8"/><stop offset="1" stop-color="#48C1C6"/></linearGradient><linearGradient id="paint1_linear" x1="137" y1="1.126" x2="1" y2="1.126" gradientUnits="userSpaceOnUse"><stop stop-color="#8FD2C8"/><stop offset="1" stop-color="#48C1C6"/></linearGradient></defs></svg>`
};
