/* 🤖 this file was generated by svg-to-ts*/
export const svgChartArrowDown: {
  name: 'chart-arrow-down';
  data: string;
} = {
  name: 'chart-arrow-down',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.667 12h4V8h-1.334v1.724l-4-4L6.667 8.39 2.47 4.195l-.942.943 5.138 5.138L9.333 7.61l3.057 3.058h-1.723V12z" fill="#929297"/></svg>`
};
