/* 🤖 this file was generated by svg-to-ts*/
export const svgSend: {
  name: 'send';
  data: string;
} = {
  name: 'send',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 4a2 2 0 012-2h7v2H4v16h16v-7h2v7a2 2 0 01-2 2H4a2 2 0 01-2-2V4zm16.586 0H13V2h9v9h-2V5.414l-7.293 7.293-1.414-1.414L18.586 4z" fill="currentColor"/></svg>`
};
