/* 🤖 this file was generated by svg-to-ts*/
export const svgInformation: {
  name: 'information';
  data: string;
} = {
  name: 'information',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><circle stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round" stroke="#fff" r="23" fill="none" cy="25" cx="25"/><path fill="#fff" d="M23.779 16.241c-.216 0-.357-.144-.357-.359v-2.618c0-.215.142-.359.357-.359h2.439c.215 0 .359.144.359.359v2.618c0 .215-.145.359-.359.359h-2.439zm.073 21.052c-.215 0-.358-.143-.358-.358V20.473c0-.215.144-.359.358-.359h2.295c.216 0 .359.144.359.359v16.462c0 .216-.144.358-.359.358h-2.295z"/></svg>`
};
