/* 🤖 this file was generated by svg-to-ts*/
export const svgReceiveCoin: {
  name: 'receive-coin';
  data: string;
} = {
  name: 'receive-coin',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#FFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-down-left" viewBox="0 0 24 24"><path d="M17 7L7 17M17 17H7V7"/></svg>`
};
