/* 🤖 this file was generated by svg-to-ts*/
export const svgExpandMore: {
  name: 'expand-more';
  data: string;
} = {
  name: 'expand-more',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M11.06 5.727L8 8.78 4.94 5.727l-.94.94 4 4 4-4-.94-.94z" fill="currentColor"/></svg>`
};
