/* 🤖 this file was generated by svg-to-ts*/
export const svgWidescreen: {
  name: 'widescreen';
  data: string;
} = {
  name: 'widescreen',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.002 3v6l-2.293-2.293-3.293 3.295L14 8.586l3.295-3.293L15.002 3h6zM21.002 21.002v-6l-2.293 2.293L15.416 14 14 15.416l3.295 3.293-2.293 2.293h6zM3 3v6l2.293-2.293 3.293 3.295 1.416-1.416-3.295-3.293L9 3H3zM3 21.002v-6l2.293 2.293L8.586 14l1.416 1.416-3.295 3.293L9 21.002H3z" fill="#929297"/></svg>`
};
