/* 🤖 this file was generated by svg-to-ts*/
export const svgUserAvatar4: {
  name: 'user-avatar-4';
  data: string;
} = {
  name: 'user-avatar-4',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><circle cx="18" cy="18" fill="#4177e0" stroke="#68bfa7" stroke-width="2" r="17"/><circle cx="14" cy="14" fill="#c97793" r="7.5"/><circle cx="24" cy="24" fill="#333" r="5"/></svg>`
};
