/* 🤖 this file was generated by svg-to-ts*/
export const svgLockAccount: {
  name: 'lock-account';
  data: string;
} = {
  name: 'lock-account',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 24"><path d="M12.996 1c-3.323 0-6 2.676-6 6v1c-1.093 0-2 .907-2 2v10c0 1.093.907 2 2 2h12c1.094 0 2-.907 2-2V10c0-1.093-.906-2-2-2V7c0-3.324-2.676-6-6-6zm0 2c2.277 0 4 1.724 4 4v1h-8V7c0-2.276 1.724-4 4-4zm-6 7h12v10h-12V10zm6 3c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" fill="#fff"/></svg>`
};
