/* 🤖 this file was generated by svg-to-ts*/
export const svgUserAvatar3: {
  name: 'user-avatar-3';
  data: string;
} = {
  name: 'user-avatar-3',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><circle cx="18" cy="18" fill="#c97793" stroke="#4177e0" stroke-width="2" r="17"/><circle cx="14" cy="14" fill="#333" r="7.5"/><circle cx="24" cy="24" fill="#68bfa7" r="5"/></svg>`
};
