/* 🤖 this file was generated by svg-to-ts*/
export const svgTrash: {
  name: 'trash';
  data: string;
} = {
  name: 'trash',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#F03167" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2" viewBox="0 0 24 24"><path d="M3 6h18M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2M10 11v6M14 11v6"/></svg>`
};
