/* 🤖 this file was generated by svg-to-ts*/
export const svgChartArrowFlat: {
  name: 'chart-arrow-flat';
  data: string;
} = {
  name: 'chart-arrow-flat',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.862 4.862L14 8l-3.138 3.138-.943-.943 1.529-1.528H2V7.333h9.448L9.919 5.805l.943-.943z" fill="#929297"/></svg>`
};
