/* 🤖 this file was generated by svg-to-ts*/
export const svgLike: {
  name: 'like';
  data: string;
} = {
  name: 'like',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14"><rect width="14" height="14" rx="7" fill="url(#paint0_linear)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M4 9c0 .709.224 1 1 1V6c-.776 0-1 .305-1 1v2zm6 0c0 .875-.914 1-1 1H6V5c0-1 .935-1 1.031-1C8 4 8 5.156 8 5v1h1c1 0 1 1 1 1v2z" fill="#fff"/><defs><linearGradient id="paint0_linear" x1="-.43" y1="14.215" x2="14.43" y2="14.215" gradientUnits="userSpaceOnUse"><stop stop-color="#74C5EE"/><stop offset=".32" stop-color="#73C2EF"/><stop offset=".53" stop-color="#6EB9F1"/><stop offset=".72" stop-color="#66AAF5"/><stop offset=".88" stop-color="#5A95FA"/><stop offset="1" stop-color="#4F80FF"/></linearGradient></defs></svg>`
};
