/* 🤖 this file was generated by svg-to-ts*/
export const svgLock: {
  name: 'lock';
  data: string;
} = {
  name: 'lock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96"><path fill="#cdcdcd" d="M80 44h-8V28C72 14.745 61.255 4 48 4S24 14.745 24 28v16h-8C9.37 44 4 49.37 4 56v24c0 6.63 5.37 12 12 12h64c6.63 0 12-5.37 12-12V56c0-6.63-5.37-12-12-12zM32 28c0-8.836 7.164-16 16-16s16 7.164 16 16v16H32V28zm52 52c0 2.21-1.79 4-4 4H16c-2.21 0-4-1.79-4-4V56c0-2.21 1.79-4 4-4h64c2.21 0 4 1.79 4 4v24z"/></svg>`
};
