/* 🤖 this file was generated by svg-to-ts*/
export const svgDynamicsNegative: {
  name: 'dynamics-negative';
  data: string;
} = {
  name: 'dynamics-negative',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137 18"><path d="M136 5L116.571.278 97.143 11 77.714 2.835l-19.428 9.083-19.429-5.083L19.43 11.83 0 3" stroke="#F03167"/><path opacity=".1" fill-rule="evenodd" clip-rule="evenodd" d="M136 5l-19.429-5-19.428 10.921-19.429-8.086-19.428 9.083-19.429-5.083-19.428 5.083L0 3v15h136V5z" fill="#F03167"/></svg>`
};
