/* 🤖 this file was generated by svg-to-ts*/
export const svgReceive: {
  name: 'receive';
  data: string;
} = {
  name: 'receive',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 4a2 2 0 012-2h7v2H4v16h16v-7h2v7a2 2 0 01-2 2H4a2 2 0 01-2-2V4z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M12.414 12.707H18v2H9v-9h2v5.586L18.293 4l1.414 1.414-7.293 7.293z" fill="currentColor"/></svg>`
};
