/* 🤖 this file was generated by svg-to-ts*/
export const svgDynamicsPositive: {
  name: 'dynamics-positive';
  data: string;
} = {
  name: 'dynamics-positive',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 16"><g clip-path="url(#url(#svg-dynamics-positive-clip))"><path fill-rule="evenodd" clip-rule="evenodd" d="M-11.35 4.944l3.042 3.378 3.042 1.405 3.042 1.28L.818 7.629 3.86 14.93l3.042-2.895 3.042-5.224 3.042-3.294 3.042 2.665 3.042-2.056 3.042 3.818 3.042 1.028 3.65-3.378 2.434-3.828 3.042.262 3.042 5.37L40.972 1v15H-15V9.979l3.65-5.035z" fill="url(#svg-dynamics-positive-linear)"/><path d="M-14.392 9.37l3.042-4.426 3.042 3.378 3.042 1.49 3.042 1.195L.818 7.629 3.86 14.93l3.042-2.895 3.042-5.224 3.042-3.294 3.042 2.665 3.042-2.056 2.929 3.773 3.155 1.073 3.042-2.77 3.042-4.09 3.042.524L37.322 7.4l3.042-5.707" stroke="#03B15E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g><defs><linearGradient id="svg-dynamics-positive-linear" x1="-26.661" y1="-5.25" x2="-26.661" y2="16" gradientUnits="userSpaceOnUse"><stop stop-color="#82C43C"/><stop offset="1" stop-color="#fff" stop-opacity=".01"/></linearGradient><clipPath id="url(#svg-dynamics-positive-clip)"><path fill="#fff" d="M0 0h40v16H0z"/></clipPath></defs></svg>`
};
