/* 🤖 this file was generated by svg-to-ts*/
export const svgFollow: {
  name: 'follow';
  data: string;
} = {
  name: 'follow',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M8 2.666a2 2 0 10.001 4.001 2 2 0 00-.001-4z" stroke="currentColor" stroke-width="1.333" stroke-miterlimit="10"/><path d="M14.628 16l-1.953-1.178L10.724 16l.516-2.222-1.722-1.49 2.271-.192.886-2.096.885 2.09 2.27.193-1.72 1.493.518 2.223z" fill="currentColor"/><path d="M8.646 13.296l-.73-.63H3.334v-.333c0-.578 2.472-1.667 4.667-1.667.938 0 1.924.2 2.747.472l.521-1.235c-1.12-.377-2.364-.57-3.268-.57-2.094 0-6 1.031-6 3V14h7.456l-.81-.704z" fill="currentColor"/></svg>`
};
