/* 🤖 this file was generated by svg-to-ts*/
export const svgChartArrowUp: {
  name: 'chart-arrow-up';
  data: string;
} = {
  name: 'chart-arrow-up',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.667 4h4v4h-1.334V6.276l-4 4L6.667 7.61 2.47 11.805l-.942-.943 5.138-5.138L9.333 8.39l3.057-3.058h-1.723V4z" fill="#929297"/></svg>`
};
