/* 🤖 this file was generated by svg-to-ts*/
export const svgSignal: {
  name: 'signal';
  data: string;
} = {
  name: 'signal',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 20"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 20h2V0h-2v20zm-6 0H4v-8h2v8zm-4 0H0v-4h2v4zm8 0H8V6h2v14z" fill="url(#paint0_linear)"/><defs><linearGradient id="paint0_linear" x1="-.43" y1="20.307" x2="14.43" y2="20.307" gradientUnits="userSpaceOnUse"><stop stop-color="#74C5EE"/><stop offset=".32" stop-color="#73C2EF"/><stop offset=".53" stop-color="#6EB9F1"/><stop offset=".72" stop-color="#66AAF5"/><stop offset=".88" stop-color="#5A95FA"/><stop offset="1" stop-color="#4F80FF"/></linearGradient></defs></svg>`
};
