/* 🤖 this file was generated by svg-to-ts*/
export const svgPlusBold: {
  name: 'plus-bold';
  data: string;
} = {
  name: 'plus-bold',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="none" d="M-1-1h582v402H-1z"/><g><path d="M28 14H18V4a2 2 0 00-4 0v10H4a2 2 0 000 4h10v10a2 2 0 004 0V18h10a2 2 0 000-4z"/></g></svg>`
};
