/* 🤖 this file was generated by svg-to-ts*/
export const svgPlus: {
  name: 'plus';
  data: string;
} = {
  name: 'plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 42"><g fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 21h38M21 2v38"/></g></svg>`
};
