/* 🤖 this file was generated by svg-to-ts*/

export type SvgIconName =
  | 'add-image'
  | 'close'
  | 'like'
  | 'logo'
  | 'notification'
  | 'plus'
  | 'settings';
export interface SvgIcon {
  name: SvgIconName;
  data: string;
}
