/* 🤖 this file was generated by svg-to-ts*/
export const svgArrowLeft: {
  name: 'arrow-left';
  data: string;
} = {
  name: 'arrow-left',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 14"><path d="M7 14l1.41-1.41L3.83 8H20V6H3.83l4.59-4.59L7 0 0 7l7 7z" fill="currentColor"/></svg>`
};
