/* 🤖 this file was generated by svg-to-ts*/
export const svgSendCoin: {
  name: 'send-coin';
  data: string;
} = {
  name: 'send-coin',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#FFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-up-right" viewBox="0 0 24 24"><path d="M7 17L17 7M7 7h10v10"/></svg>`
};
