/* 🤖 this file was generated by svg-to-ts*/
export const svgReload: {
  name: 'reload';
  data: string;
} = {
  name: 'reload',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><mask id="a" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><path d="M0 12h6v2H0v10h24V12h-6v-2h6V0H0v12z" fill="#fff"/></mask><g mask="url(#a)" fill="currentColor"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 5a7 7 0 100 14 7 7 0 000-14zm-9 7a9 9 0 1118 0 9 9 0 01-18 0z"/><path d="M14 10h7V3l-7 7zM10 14H3v7l7-7z"/></g></svg>`
};
