/* 🤖 this file was generated by svg-to-ts*/
export const svgImportAccount: {
  name: 'import-account';
  data: string;
} = {
  name: 'import-account',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 24"><g clip-path="url(#svg-import-account)"><path d="M6.996 2c-1.1 0-2 .9-2 2v9.172l1.414 1.414.586.586V4h12v16h-7.171l-1.414 1.414-.586.586h9.171a2 2 0 002-2V4a2 2 0 00-2-2h-12zm5 4a2 2 0 100 4 2 2 0 000-4zm0 5c-1 0-3 .628-3 1.875V14h6v-1.125c0-1.247-1.999-1.875-3-1.875zm-7 5v3h-4v2h4v3l4-4-4-4z" fill="currentColor"/></g><defs><clipPath id="svg-import-account"><path fill="#fff" transform="translate(.996)" d="M0 0h24v24H0z"/></clipPath></defs></svg>`
};
