/* 🤖 this file was generated by svg-to-ts*/
export const svgPdvRateIcon: {
  name: 'pdv-rate-icon';
  data: string;
} = {
  name: 'pdv-rate-icon',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="#6BBFA6" d="M0 16c0 8.836 7.164 16 16.004 16C24.836 32 32 24.836 32 16c0-8.838-7.164-16-15.996-16C7.164 0 0 7.162 0 16zm24-.031h-6V24h-4v-8.031H8.031l7.973-7.971L24 15.969z"/></svg>`
};
