/* 🤖 this file was generated by svg-to-ts*/
export const svgDynamicsNegative: {
  name: 'dynamics-negative';
  data: string;
} = {
  name: 'dynamics-negative',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 16"><g clip-path="url(#svg-dynamics-negative-clip)"><path fill-rule="evenodd" clip-rule="evenodd" d="M-12.271 13.786l3.107-2.143 3.107 2.678 3.107-4.285 3.107 2.143h3.107l3.107-4.822L9.48 5.75l3.107 1.607L15.693 2 18.8 7.357l3.107-1.071 3.107-2.679 3.729 2.143 2.486-.804 3.107.268L37.443 2l3.728 5.893V17H-16v-4.286l3.729 1.072z" fill="url(#svg-dynamics-negative-linear)"/><path d="M-15.379 12.714l3.108 1.072 3.107-2.143 3.107 2.143 3.107-3.75 3.107 2.143h3.107l3.107-4.822L9.48 5.75l3.107 1.607L15.693 2 18.8 7.357l3.107-1.071 3.107-2.679 3.108 2.143 3.107-1.071 3.107.535L37.443 2l3.107 5.357" stroke="#FA5454" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g><defs><linearGradient id="svg-dynamics-negative-linear" x1="-27.911" y1="-4.25" x2="-27.911" y2="17" gradientUnits="userSpaceOnUse"><stop stop-color="#FC5A5A"/><stop offset="1" stop-color="#fff" stop-opacity=".01"/></linearGradient><clipPath id="url(#svg-dynamics-negative-clip)"><path fill="#fff" d="M0 0h40v16H0z"/></clipPath></defs></svg>`
};
