/* 🤖 this file was generated by svg-to-ts*/
export const svgAdd: {
  name: 'add';
  data: string;
} = {
  name: 'add',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M12.667 8.667h-4v4H7.334v-4h-4V7.333h4v-4h1.333v4h4v1.334z" fill="currentColor"/></svg>`
};
