/* 🤖 this file was generated by svg-to-ts*/
export const svgUserAvatar5: {
  name: 'user-avatar-5';
  data: string;
} = {
  name: 'user-avatar-5',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><circle cx="18" cy="18" fill="#68bfa7" stroke="#333" stroke-width="2" r="17"/><circle cx="14" cy="14" fill="#4177e0" r="7.5"/><circle cx="24" cy="24" fill="#333" r="5"/></svg>`
};
