/* 🤖 this file was generated by svg-to-ts*/
export const svgPlusSmall: {
  name: 'plus-small';
  data: string;
} = {
  name: 'plus-small',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14"><path d="M14 6.5v1a.5.5 0 01-.5.5H8v5.5a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5V8H.5a.5.5 0 01-.5-.5v-1A.5.5 0 01.5 6H6V.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5V6h5.5a.5.5 0 01.5.5z" fill="#fff"/></svg>`
};
