/* 🤖 this file was generated by svg-to-ts*/
export const svgClose: {
  name: 'close';
  data: string;
} = {
  name: 'close',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="none" d="M-1-1h582v402H-1z"/><g><path stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="#000" fill="none" class="cls-1" d="M7 7l18 18M7 25L25 7"/></g></svg>`
};
