/* 🤖 this file was generated by svg-to-ts*/
export const svgSignal: {
  name: 'signal';
  data: string;
} = {
  name: 'signal',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="currentColor" d="M3 16h3v4H3zM8 12h3v8H8zM13 8h3v12h-3zM18 4h3v16h-3z"/></svg>`
};
