/* 🤖 this file was generated by svg-to-ts*/
export const svgNotification: {
  name: 'notification';
  data: string;
} = {
  name: 'notification',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="none" d="M-1-1h582v402H-1z"/><g><path d="M27 27.072H5a1 1 0 01-.89-1.45 18.14 18.14 0 001.89-8v-3.55a10 10 0 0120 0v3.53a18.14 18.14 0 001.89 8 1 1 0 01-.89 1.47zm-20.45-2h18.9a20.14 20.14 0 01-1.45-7.47v-3.53a8 8 0 00-16 0v3.53a20.14 20.14 0 01-1.45 7.47z" class="cls-1"/><path d="M16 31a5 5 0 01-5-5 1 1 0 012 0 3 3 0 00.88 2.12 3.08 3.08 0 004.24 0 1 1 0 011.42 1.42A5 5 0 0116 31zM16 6a1 1 0 01-1-1V2a1 1 0 012 0v3a1 1 0 01-1 1zM26 5a2 2 0 112-2 2 2 0 01-2 2zm0-2zm0 0zm0 0zm0 0zm0 0zm0 0zm0 0zm0 0z" class="cls-1"/></g></svg>`
};
