/* 🤖 this file was generated by svg-to-ts*/

export type SvgIconName =
  | 'add-image'
  | 'arrow-left'
  | 'chart-arrow-down'
  | 'chart-arrow-flat'
  | 'chart-arrow-up'
  | 'check'
  | 'close'
  | 'decentr-hub'
  | 'delete'
  | 'dropdown-expand'
  | 'dynamics-negative'
  | 'dynamics-positive'
  | 'edit'
  | 'expand-more'
  | 'follow'
  | 'import-account'
  | 'import'
  | 'information'
  | 'like'
  | 'lock-account'
  | 'lock'
  | 'logo-icon'
  | 'logo'
  | 'pdv-rate-icon'
  | 'plus'
  | 'publish'
  | 'receive-coin'
  | 'reload'
  | 'send-coin'
  | 'settings'
  | 'trash';
export interface SvgIcon {
  name: SvgIconName;
  data: string;
}
