/* 🤖 this file was generated by svg-to-ts*/
export const svgMarginNegative: {
  name: 'margin-negative';
  data: string;
} = {
  name: 'margin-negative',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11 11"><path d="M1.05 1.522l.472-.472c.13-.13.34-.13.47 0l7.624 7.623-.005-4.19a.333.333 0 01.335-.336l.664.005a.333.333 0 01.335.335l.005 5.784a.5.5 0 01-.146.353l-.18.18a.514.514 0 01-.353.146l-5.784-.005a.333.333 0 01-.335-.335v-.669a.327.327 0 01.33-.33l4.19.005L1.05 1.993a.333.333 0 010-.471z" fill="#FC5A5A"/></svg>`
};
