/* 🤖 this file was generated by svg-to-ts*/

export type SvgIconName =
  | 'add-image'
  | 'close'
  | 'dynamics-negative'
  | 'dynamics-positive'
  | 'like'
  | 'lock'
  | 'logo'
  | 'notification'
  | 'pdv-rate-icon'
  | 'plus'
  | 'settings'
  | 'signal'
  | 'trash';
export interface SvgIcon {
  name: SvgIconName;
  data: string;
}
