/* 🤖 this file was generated by svg-to-ts*/
export const svgImport: {
  name: 'import';
  data: string;
} = {
  name: 'import',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 185.208 185.208"><g fill="none" stroke="#000" stroke-width="9.26" stroke-linecap="round" stroke-linejoin="round"><path stroke-miterlimit="6.2" d="M180.58 128.369v50.635c0 1.263-.842 2.28-1.89 2.28H6.518c-1.047 0-1.89-1.017-1.89-2.28v-50.635"/><path d="M92.604 3.99v150.835M92.604 154.825L49.122 110.4M92.604 154.825l43.482-44.424"/></g></svg>`
};
