/* 🤖 this file was generated by svg-to-ts*/
export const svgMarginNeutral: {
  name: 'margin-neutral';
  data: string;
} = {
  name: 'margin-neutral',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11 11"><path d="M1.522 9.95l-.472-.472a.333.333 0 010-.471l7.623-7.623-4.191.005a.333.333 0 01-.335-.335L4.152.39a.333.333 0 01.335-.335L10.27.05a.5.5 0 01.353.146l.18.18a.514.514 0 01.146.353l-.005 5.784a.333.333 0 01-.335.335h-.67a.327.327 0 01-.33-.33l.006-4.19L1.993 9.95a.333.333 0 01-.472 0z" fill="#92929D"/></svg>`
};
