/* 🤖 this file was generated by svg-to-ts*/
export const svgDelete: {
  name: 'delete';
  data: string;
} = {
  name: 'delete',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M6.667 1.333L6 2H2.667v1.333h.666v10c0 .729.605 1.334 1.333 1.334h6.667c.729 0 1.333-.605 1.333-1.334v-10h.667V2H10l-.667-.667H6.666zm-2 2h6.666v10H4.666v-10zM6.47 5.53l-.943.942L7.058 8l-1.53 1.529.943.942L8 8.943l1.528 1.528.943-.942-1.528-1.53 1.528-1.528-.943-.942L8 7.057 6.47 5.53z" fill="currentColor"/></svg>`
};
